### ISSUE TITLE
Don't assign tasks to users who are away

### ISSUE THREAD

**Issue by tatey** [fivegoodfriends/robin#2]
I was away on leave last week but tasks kept getting assigned to me even though everyone knew I was away. It would be nice if Robin knew I was away and just excluded me from assignment.

Could we potentially [leverage statuses](https://slackhq.com/set-your-status-in-slack-28a793914b98) in Slack?

**Comment by atcruice** [comment]
Moved to Basecamp todo, https://3.basecamp.com/3653596/buckets/6781286/todos/961276548.
