### ISSUE TITLE
Don't assign tasks to the instigator of the task

### ISSUE THREAD

**Issue by tatey** [fivegoodfriends/robin#3]
We round robin reviewing PRs. If I create a PR and it's my turn to go next, then I get assigned the task in Slack. I get around this by reassigning now, but it would be nice if it just knew I was that person.

Thinking the best way to do this would be to take the usernames/IDs of users who should be excluded from assignment as a parameter to the webhook endpoint.

That way we could make our Zap look at the incoming payload from GitHub, map the GitHub username to the Slack username, and then pass the parameter.

**Comment by atcruice** [comment]
Moved to Basecamp todo, https://3.basecamp.com/3653596/buckets/6781286/todos/961257329.
