### ISSUE TITLE
Find it hard to track what I have been assigned

### ISSUE THREAD

**Issue by aldhsu** [fivegoodfriends/robin#5]
## Example
- Accepted PR review
  - should assign me as reviewer in Github

**Comment by tatey** [comment]
If we made actioning a task perform a webhook we could leverage Zapier to do the assignment. It also gives us the most flexibility to think about other integrations without increasing the surface area of Robin.

What do you think?

**Comment by tatey** [comment]
Robin actually tracks which tasks you've actioned. We could potentially build a command like `/robin tasks` which show the 10 most recent tasks you've actioned.

**Comment by atcruice** [comment]
When https://3.basecamp.com/3653596/buckets/6781286/todos/963562195 is actioned, this issue will disappear as we'll be able to wire up zaps to handle auto-assigning tasks in other systems.
